[package]
name = "classfile-parser"
description = "A parser for Java Class files written in rust"
version = "0.3.4"
authors = ["Nick Palmer <nick@palmr.co.uk>"]
keywords = ["java", "parsing", "class", "classfile"]
categories = ["parser-implementations"]
repository = "https://github.com/Palmr/classfile-parser"
readme = "README.md"
license-file = "LICENSE.txt"
exclude = [".idea/**/*", "classfile-parser.iml", "java-assets/out/**/*"]

[badges]
travis-ci = { repository = "Palmr/classfile-parser" }

[dependencies]
nom = "^4.1"
bitflags = "^1.0"
cesu8 = "^1.1"
